# Generated by Django 5.0 on 2023-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='extra_content',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=250),
        ),
    ]
