# Generated by Django 5.0 on 2023-12-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sources',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
